version: "3.8"
# services: 
#     db:
#         image: "postgres:12"
#         ports: 
#             - "54320:5432"
#         volumes: 
#             - ./pgdata:/var/lib/postgresql/data
#         environment: 
#             - POSTGRES_USER=test
#             - POSTGRES_PASSWORD=test
#             - POSTGRES_DB=test

services:
  # app:
  #   image: sample:1.0
  #   container_name: sample_app
  #   build: .
  #   ports:
  #     - 80:3000
  #   environment:
  #     - MONGO_URI=mongodb://sampledb/sample
  #   depends_on:
  #     - db
  #   networks:
  #     - samplenet
  db:
    image: mongo:3.0.15
    container_name: sample_db
    volumes:
      - ./db:/data/db
    # this was suddenly requred for some reasons...
    ports:
      - "27017:27017"
#     networks:
#       samplenet:
#         aliases:
#           - "sampledb"
# networks:
#   samplenet:
#     driver: bridge
